import { Subject } from './card';

export const SUBJECTS: Subject[] = [
  {
    subjects: [
      'Mathematik',
      'Physik',
      'Elektrotechnik',
      'Informatik',
      'Chemie',
      'Biologie',
      'Architektur',
      'Bauwesen',
      'Wirtschaft',
      'Verkehrswesen',
      'Sport',
      'Psychologie',
      'Pädagogik',
      'Geographie',
      'Jura',
      'Linguistik',
      'Kunst',
      'Literatur',
      'Musik',
      'Gestaltung',
      'Religion',
      'Ethik',
      'Kultur',
      'Archäologie',
      'Bildung',
      'Kommunikation',
      'Verschiedenes',
      'Mode',
      'Ökologie',
      'Geschichte',
      'Gesundheit',
      'Medizin',
      'Betriebswirtschaft',
      'Politik',
      'Ingenieurwesen',
      'Technik',
    ],
  },
];
