import { Subject } from './card';

export const SUBJECTS: Subject[] = [
  { name: 'Mathematik' },
  { name: 'Physik' },
  { name: 'Elektrotechnik' },
  { name: 'Informatik' },
  { name: 'Chemie' },
  { name: 'Biologie' },
  { name: 'Architektur' },
  { name: 'Bauwesen' },
  { name: 'Wirtschaft' },
  { name: 'Verkehrswesen' },
  { name: 'Sport' },
  { name: 'Psychologie' },
  { name: 'Pädagogik' },
  { name: 'Geographie' },
  { name: 'Jura' },
  { name: 'Linguistik' },
  { name: 'Kunst' },
  { name: 'Literatur' },
  { name: 'Musik' },
  { name: 'Gestaltung' },
  { name: 'Religion' },
  { name: 'Ethik' },
  { name: 'Kultur' },
  { name: 'Archäologie' },
  { name: 'Bildung' },
  { name: 'Kommunikation' },
  { name: 'Verschiedenes' },
  { name: 'Mode' },
  { name: 'Ökologie' },
  { name: 'Geschichte' },
  { name: 'Gesundheit' },
  { name: 'Medizin' },
  { name: 'Betriebswirtschaft' },
  { name: 'Politik' },
  { name: 'Ingenieurwesen' },
  { name: 'Technik' },
];
